'use client';
import { ColorSchemeScript } from '@mantine/core';
import { Viewport } from 'next';
import './globals.css';

import { cn } from '@rng-apps/forms';
import dynamic from 'next/dynamic';
const LayoutClient = dynamic(() => import('./layout-client'), { ssr: false });

// const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'RNG Books',
//   // description: 'Generated by create-nx-workspace',
// };

export const viewport: Viewport = {
  initialScale: 1,
  maximumScale: 1,
  minimumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
        <title>RNG Books</title>
      </head>

      <body
        className={cn(
          // inter.className,
          'relative flex flex-col h-[100dvh] w-[100dvw] max-w-[100dvw] max-h-[100dvh] overflow-hidden'
        )}
      >
        <LayoutClient>{children}</LayoutClient>
      </body>
    </html>
  );
}
